{"version":1,"ops":[{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521131662,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzQ0MDI5OA==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373440298"},"message":"- Did you start with a config.ini or let keepmenu generate it on first run?\n- Either way, can you please post the config.ini that you are using.\n\nThanks!\n\nEdit: also, did you just install within the last 10 or 15 minutes, or was it awhile ago, because I just did some updating this morning.","files":null},{"type":3,"author":{"id":"4834f56d14f9a8cd6b243569767a65b9893bc972"},"timestamp":1521133789,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzQ1MjQ5NA==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373452494"},"message":"Installed a day or two ago and let keepmenu create the config, then edited in location of my database.\nconfig.ini:  http://ix.io/XrQ","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521133924,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzQ1MzI0NQ==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373453245"},"message":"I think I see where the bug is... hopefully I'll have it fixed today! Thanks for the report!","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521134290,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzQ1NTMyMA==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373455320"},"message":"Oh, and in the meantime, just add a section `[dmenu]` to your config.ini.  That should get it working for now.","files":null},{"type":3,"author":{"id":"4834f56d14f9a8cd6b243569767a65b9893bc972"},"timestamp":1521134526,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzQ1NjY4NA==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373456684"},"message":"Oh yeah forgot to mention I was intending to try this with rofi, should I have [dmenu] or [rofi] in my config depending on which one I want to use?","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521135293,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzQ2MDkzNw==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373460937"},"message":"No, just the `[dmenu]` section with ` dmenu_command = rofi`.","files":null},{"type":3,"author":{"id":"4834f56d14f9a8cd6b243569767a65b9893bc972"},"timestamp":1521140056,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzQ4NTczOA==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373485738"},"message":"Updated config to: http://ix.io/XuR\n\nkeepmenu says invalid pw, even though said pw is correct and works with keepass(mono based v.program).","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521140545,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzQ4ODExNw==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373488117"},"message":"Hrm. That's tougher to troubleshoot from here...\n\n* doublecheck your keyfile is spelled correctly in config.ini\n* Try adding your passphrase to config.ini and see if that works\n* Any non-US or funky characters in the password?\n\nIf you still have trouble, we could chat on IRC and see if we can solve it real time.","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521148367,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzUyNDYyMQ==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373524621"},"message":"Any chance you can test the develop branch for me before I push to master? Pretty sure I squashed the initial bug you reported.  If you're not comfortable with that, no worries.\n\nAlso let me know if you get it working with your password/keyfile.\n\nThanks for your patience!\n\nEdit: if you do test develop, please delete your config.ini and start from scratch.","files":null},{"type":3,"author":{"id":"4834f56d14f9a8cd6b243569767a65b9893bc972"},"timestamp":1521157212,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzU1NjkxMA==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373556910"},"message":"Starting to wonder if it is something in my database causing an error...\nhttp://ix.io/XC0\n\nconfig: http://ix.io/XC3\ndoesn't include actual pw but its just english letters \u0026 numbers","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521157326,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzU1NzIzNA==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373557234"},"message":"Ah, yes...I saw that before and thought I fixed it so it wouldn't error out on bad characters in the database. Standby...","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521157658,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzU1ODIxNA==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373558214"},"message":"Are you using python 2 or 3? Any chance you can troll through your database and see if you can find an odd character someplace and maybe create a new database using keepass just with a one fake entry containing that character? If the database is too large, I understand and I'll see what I can do.","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521158013,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzU1OTIyMA==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373559220"},"message":"You must be using python2. I made a entry with that character Ã© and it's erroring out. Works fine with python3. Sigh. It's tempting to drop support for 2, but I'll see if I can work around it. Unicode support is horrible...","files":null},{"type":3,"author":{"id":"4834f56d14f9a8cd6b243569767a65b9893bc972"},"timestamp":1521158359,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzU2MDE1Mw==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373560153"},"message":"Should be using 3 as thats the default on Arch.","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521158687,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzU2MTIwOA==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373561208"},"message":"You might wanna check that...I'm almost positive that you're using python2 to run keepmenu because of the error. I get the _exact_ error that you did when I run it using python2!","files":null},{"type":3,"author":{"id":"4834f56d14f9a8cd6b243569767a65b9893bc972"},"timestamp":1521159814,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzU2NDM2OA==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373564368"},"message":"`$ python -V\nPython 3.6.4`\n\nIt seems to be something in my database anyways as keepmenu has no issue opening a newly created one. I have opened \u0026 edited the database in Arch, Android and Windows so I guess this is just my error as anyone of the clients could have left a character they shouldn't have or doesn't transfer across OS' well.","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521160407,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzU2NjAwNw==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373566007"},"message":"That's very odd...not normally an error message you see when using python 3. Anyway...sounds like you've got access to your database now that you've sorted the error?  I'll still try and make it more robust so at least it won't crash on a bad character.\n\nAny other issues you've found yet? I really appreciate the feedback!","files":null},{"type":3,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521211534,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDM3MzczNTQ2Mg==","github-url":"https://github.com/firecat53/keepmenu/issues/4#issuecomment-373735462"},"message":"I pushed a fix to the develop branch for Unicode characters in the database that should fix any issues with Python 2. Hopefully this fixes the last of your keepmenu issues for now!","files":null},{"type":4,"author":{"id":"3c87de25ab8b2ec3449081ec888ea2a273bb79fc"},"timestamp":1521406877,"metadata":{"github-id":"MDExOkNsb3NlZEV2ZW50MTUyNzQyNTI4OA=="},"status":2}]}